# Generated by Django 4.1.5 on 2023-01-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_customuser_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
